# Default values for ratify.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: v2

notation:
  scope: []
  trustedIdentities: []
  certs: []
  
stores:
  - scope: "docker.io"
    username: ""
    password: ""