# permissions for end users to edit namespacedkeymanagementproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: namespacedkeymanagementprovider-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ratify
    app.kubernetes.io/part-of: ratify
    app.kubernetes.io/managed-by: kustomize
  name: namespacedkeymanagementprovider-editor-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedkeymanagementproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedkeymanagementproviders/status
  verbs:
  - get
