apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-dynamic
spec:
  name: dynamic
  artifactTypes: application/vnd.ratify.spdx.v0
  source:
    artifact: wabbitnetworks.azurecr.io/test/sample-verifier-plugin:v1
