apiVersion: config.ratify.deislabs.io/v1beta1
kind: NamespacedVerifier
metadata:
  name: verifier-vulnerabilityreport
spec:
  name: vulnerabilityreport
  artifactTypes: application/sarif+json
  parameters:
    maximumAge: 24h
    disallowedSeverities:
      - high
      - critical
    denylistCVEs:
      - CVE-2021-44228 # Log4Shell
