apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: schemavalidator
spec:
  name: schemavalidator
  artifactTypes: vnd.aquasecurity.trivy.report.sarif.v1
  parameters: 
    schemas:
      application/sarif+json: https://json.schemastore.org/sourcehut-build-0.65.0.json
