apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Store
metadata:
  name: store-orask8secret
spec:
  name: oras
  parameters:
    cosign-enabled: false    
    authProvider:
      name: k8Secrets
      secrets: 
      - secretName: myregistrykey