apiVersion: config.ratify.deislabs.io/v1beta1
kind: Store
metadata:
  name: store-oras
spec:
  name: oras  
  parameters:
    # NOTE: docker auth provider selected by default if none specified
    cacheEnabled: true
    capacity: 100
    cosignEnabled: false
    keyNumber: 10000
    ttl: 10
    useHttp: true