{{- $subject := printf "/CN=%s.%s" (include "ratify.fullname" .) .Release.Namespace -}}
{{- $dns := printf "%s.%s" (include "ratify.fullname" .) .Release.Namespace -}}
{{- $ca := genCA "/O=Ratify/CN=Ratify Root CA" 365 -}}
{{- $cert := genSignedCert $subject nil (list $dns) 365 $ca -}}
{{- $tlsSecret := printf "%s-tls" (include "ratify.fullname" .) -}}

---

{{ include "ratify.providerGKVersion" . }}
kind: Provider
metadata:
  name: ratify-provider
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v1/verify
  timeout: {{ required "You must provide .Values.provider.timeout.validationTimeoutSeconds" .Values.provider.timeout.validationTimeoutSeconds }}
  {{ include "ratify.providerCabundle" (list . $ca) | nindent 2}}

---

{{ include "ratify.providerGKVersion" . }}
kind: Provider
metadata:
  name: ratify-mutation-provider
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v1/mutate
  timeout: {{ required "You must provide .Values.provider.timeout.mutationTimeoutSeconds" .Values.provider.timeout.mutationTimeoutSeconds }}
  {{ include "ratify.providerCabundle" (list . $ca) | nindent 2}}

---
{{- if or (not .Values.featureFlags.RATIFY_CERT_ROTATION) (and .Values.provider.tls.crt .Values.provider.tls.key .Values.provider.tls.cabundle .Values.provider.tls.caCert .Values.provider.tls.caKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
data:
  {{ include "ratify.tlsSecret" (list . $cert $ca) | nindent 2}}
{{- else if not (lookup "v1" "Secret" .Release.Namespace $tlsSecret ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
data:
{{- end }}