{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ratify-manager-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/finalizers
  verbs:
  - update
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/status
  verbs:
  - get
  - patch
  - update
  {{- end }}
