apiVersion: config.ratify.deislabs.io/v1beta1
kind: Store
metadata:
  name: store-oras
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  name: oras
  parameters:
    {{- if .Values.oras.useHttp }}
    useHttp: true
    {{- end }}
    {{- if .Values.cosign.enabled }}
    cosignEnabled: true
    {{- end }}
    {{- if .Values.oras.authProviders.azureWorkloadIdentityEnabled }}
    authProvider:
      name: azureWorkloadIdentity
      clientID: {{ .Values.azureWorkloadIdentity.clientId }}
    {{- end }}
    {{- if .Values.oras.authProviders.azureManagedIdentityEnabled }}
    authProvider:
      name: azureManagedIdentity
      clientID: {{ .Values.azureManagedIdentity.clientId }}
    {{- end }}
    {{- if .Values.oras.authProviders.k8secretsEnabled }}
    authProvider:
      name: k8Secrets
      serviceAccountName: {{ include "ratify.serviceAccountName" . }} 
    {{- end }}
    {{- if .Values.oras.authProviders.awsEcrBasicEnabled }}
    authProvider:
      name: awsEcrBasic
    {{- end }}
    {{- if .Values.oras.cache.enabled }}
    cacheEnabled: true
    ttl: {{ .Values.oras.cache.ttl }}
    {{- end }}
