---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: clusterstores.config.ratify.deislabs.io
spec:
  group: config.ratify.deislabs.io
  names:
    kind: ClusterStore
    listKind: ClusterStoreList
    plural: clusterstores
    singular: clusterstore
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ClusterStore is the Schema for the clusterstores API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterStoreSpec defines the desired state of ClusterStore
            properties:
              address:
                description: Plugin path, optional
                type: string
              name:
                description: Name of the cluster store
                type: string
              parameters:
                description: Parameters of the cluster store
                type: object
                x-kubernetes-preserve-unknown-fields: true
              source:
                description: OCI Artifact source to download the plugin from, optional
                properties:
                  artifact:
                    description: OCI Artifact source to download the plugin from
                    type: string
                  authProvider:
                    description: AuthProvider to use to authenticate to the OCI Artifact
                      source, optional
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                type: object
              version:
                description: Version of the cluster store plugin. Optional
                type: string
            required:
            - name
            type: object
          status:
            description: ClusterStoreStatus defines the observed state of ClusterStore
            type: object
        type: object
    served: true
    storage: true
