name: pr_to_main

on:
  push:
    branches:
      - 'dev'

permissions:
  pull-requests: write

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      
      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request with reposync action
        id: open-pr
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 #v2.12.1
        with:
          github_token: ${{ secrets.PR_TOKEN }}
          destination_branch: main
          pr_title: ${{ github.event.commits[0].message }}
          pr_body: "Automated Pull Request"
