name: pr_to_main

on:
  schedule:
    - cron: "30 8 * * 0" # early morning (08:30 UTC) every Sunday
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: create pull request with reposync action
        id: open-pr
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 #v2.12.1
        with:
          source_branch: v1-dev
          destination_branch: v1
          pr_title: "chore: automated PR to v1 ${{ steps.date.outputs.date }}"
          pr_body: "Automated Pull Request to v1 branch"
