name: run-full-validation

on:
  pull_request:
    branches:
      - main
      - release*
  push:
    branches:
      - main
      - release*
  workflow_dispatch:

permissions: read-all

jobs:
  call-e2e-cli:
    uses: ./.github/workflows/e2e-cli.yml

  call_test_e2e_full:
    name: "Build and run e2e on full test matrix"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSION: ["1.30.6", "1.31.2"]
        GATEKEEPER_VERSION: ["3.16.0", "3.17.0", "3.18.0"]
    uses: ./.github/workflows/e2e-k8s.yml
    with:
      k8s_version: ${{ matrix.KUBERNETES_VERSION }}
      gatekeeper_version: ${{ matrix.GATEKEEPER_VERSION }}

  build_test_aks_e2e:
    name: "Build and run e2e Test on AKS"
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSION: ["1.30.6", "1.31.2"]
        GATEKEEPER_VERSION: ["3.16.0", "3.17.0", "3.18.0"]
    uses: ./.github/workflows/e2e-aks.yml
    with:
      k8s_version: ${{ matrix.KUBERNETES_VERSION }}
      gatekeeper_version: ${{ matrix.GATEKEEPER_VERSION }}
    secrets: inherit

  aks-test-cleanup:
    env:
      AZURE_SUBSCRIPTION_ID: daae1e1a-63dc-454f-825d-b39289070f79
      AZURE_CLIENT_ID: 814e6e97-120c-4534-b8a9-f1645bc99500
      AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
    needs: ['build_test_aks_e2e']
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: azure-test
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Go 1.23
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.23'

      - name: Az CLI login
        uses: azure/login@6b2456866fc08b011acb422a92a4aa20e2c4de32 # v2.1.0
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: clean up
        run: |
          make e2e-cleanup AZURE_SUBSCRIPTION_ID=${{ env.AZURE_SUBSCRIPTION_ID }}